### ISSUE TITLE
Document X509 version is 0-index based

### ISSUE THREAD

**Issue by slamora** [M2Crypto/M2Crypto#25]
Include some reference to the use of a 0-index on X509 version field will avoid creating invalid certificates:

User creates an unexistent X509 v4
```python
from M2Crypto import X509

cert = X509.X509()
cert.set_version(3)
```

But he didn't realize except by checking certificate details:

    $ openssl x509 -in thawte-ca-certificate.pem -noout -text
    Certificate:
       Data:
           Version: 4 (0x3)
           Serial Number: 1 (0x1)
           Signature Algorithm: md5WithRSAEncryption
           ....

How about including some reference on the docstring of ``get_version()`` and ``set_version()`` methods on class ``X509``?

**Comment by mcepl** [comment]
Please, file a ticket at https://github.com/martinpaljak/M2Crypto/issues. This repo is now dead and unmaintained.
