### ISSUE TITLE
Building problems under PyEnv, Yosemite

### ISSUE THREAD

**Issue by dsoprea** [M2Crypto/M2Crypto#28]
As mentioned at https://github.com/python-greenlet/greenlet/issues/74, I had to define CC to prevent the build from trying to invoke "python.exe". However, now I get: "Unknown option: -D".

```
$ CC=$(which python) pip install M2Crypto
```

This results in:

```
    creating build/temp.macosx-10.10-x86_64-2.7
    creating build/temp.macosx-10.10-x86_64-2.7/SWIG
    /Users/dustin/.pyenv/shims/python -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Qunused-arguments -Qunused-arguments -I/Users/dustin/.pyenv/versions/2.7.6/include/python2.7 -I/usr/include -I/private/var/folders/qk/t5991kt11cb2y6qgmzrzm_g00000gp/T/pip-build-5bKvxK/M2Crypto/SWIG -c SWIG/_m2crypto_wrap.c -o build/temp.macosx-10.10-x86_64-2.7/SWIG/_m2crypto_wrap.o -DTHREADING -Wno-deprecated-declarations
    Unknown option: -D
    usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
    Try `python -h' for more information.
    error: command '/Users/dustin/.pyenv/shims/python' failed with exit status 2
```

Is M2Crypto sending this in? How do I prevent/modify it?

**Comment by mcepl** [comment]
I am not sure about the solution to your problem, but you certainly should NOT redefine `CC`. That should be C compiler, and you need it for building M2Crypto (and it should be the system one, so the same as the one which build /usr/bin/python itself).
