### ISSUE TITLE
Any schedule to merge https://github.com/M2Crypto/M2Crypto/ and https://github.com/martinpaljak/M2Crypto?

### ISSUE THREAD

**Issue by idgserpro** [M2Crypto/M2Crypto#36]
We're asking if it's possible to have a new release in https://github.com/martinpaljak/M2Crypto/issues/52 from @martinpaljak since in that repository there's a better fix for identifying Red Hat distributions (a distro that is heavily used in enterprise).

Fact is, these both M2Crypto repositories are out of sync and it's confusing to know which one is really the canonical one. If something could enlighten us about the future of both repositories we would really appreciate. Thanks!

**Comment by mcepl** [comment]
This repository is completely unmaintained and if you want anything, you should better ask @martinpaljak .

**Comment by idgserpro** [comment]
We asked this question because in https://github.com/martinpaljak/M2Crypto/issues/52, we have in ```README.md```:

```
The official repository shall soon live at https://github.com/M2Crypto/M2Crypto.
```

So, is this repository completely unrelated to martinpaljak?
